version: '2'
services:
    learnjhipster-app:
        image: learnjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://learnjhipster-postgresql:5432/learnjhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    learnjhipster-postgresql:
        extends:
            file: postgresql.yml
            service: learnjhipster-postgresql
